#! /usr/bin/python3


import argparse
import subprocess
import re


def getSinks():
    output = subprocess.check_output('pactl list sinks',
                                     shell=True,
                                     stderr=subprocess.STDOUT,
                                     universal_newlines=True)
    res = list(filter(lambda x: 'Sink #' in x,
               re.split('\n', str(output).replace('\\n\\n', '\n'))))
    res = list(map(lambda x: int(x.strip('Sink #')), res))
    return res
 

def getVolume():
    output = subprocess.check_output('pactl list sinks',
                                     shell=True,
                                     stderr=subprocess.STDOUT)
    res = re.split('\n', str(output).replace('\\n\\n', '\n'))[0]
    res = list(filter(lambda x: 'Volume: front' in x,
               res.split('\\n')))[0]
    return int(re.split(' +', res)[4].strip('%').strip())


def up():
    sinks = getSinks()
    volume = getVolume()
    volume = min(100, volume + 5)
    for sink in sinks:
        subprocess.check_output(
                'pactl set-sink-volume {} {}\%'.format(sink, volume),
                shell=True,
                stderr=subprocess.STDOUT)


def down():
    sinks = getSinks()
    volume = getVolume()
    volume = max(0, volume - 5)
    for sink in sinks:
        subprocess.check_output(
                'pactl set-sink-volume {} {}\%'.format(sink, volume),
                shell=True,
                stderr=subprocess.STDOUT)


def mute():
    sinks = getSinks()
    for sink in sinks:
        subprocess.check_output(
                'pactl set-sink-mute {} toggle'.format(sink),
                shell=True,
                stderr=subprocess.STDOUT)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('cmd', help='[up] to increase volume '
                                    '[down] to decrease volume '
                                    '[mute] to toggle mute '
                                    '[get] to get volume'
                       )
    args = parser.parse_args()
    if args.cmd == 'up':
        up()
    elif args.cmd == 'down':
        down()
    elif args.cmd == 'mute':
        mute()
    elif args.cmd == 'get':
        print(getVolume())
    else:
        print('wtf you tryna do bro')


if __name__ == '__main__':
    main()
